### ISSUE TITLE
_run:_get_scan:  echo of the command does not match (line @1):

### ISSUE THREAD

**Issue by joelmaranhao** [simondlevy/BreezySLAM#7]
# Environment

- Using LiDAR URG-04LX (Hokuyo Automatic Co.,Ltd.)
- Python 2.7.6

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

```
$ uname -a
Linux mycomputer 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

# Error

The application opens for a few seconds and starts building the image, then it crashes ...
This happens rather randomly from a user perspective, sometimes the app lives several minutes before a crash

```
$ ./BreezySLAM/examples/urgslam.py
```
```
init done 
opengl support available 
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run: _confirm_scan: response does not match the echo of the command (line 1)
_run:_get_scan:  could not confirm scan!
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  response does not match (line @2):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  response does not match (line @2):
_run:_find_packet_start: not connected to the sensor!
Traceback (most recent call last):
  File "./BreezySLAM/examples/urgslam.py", line 53, in <module>
    slam.update(lidar.getScan())
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 254, in update
    CoreSLAM.update(self, scan_mm, velocities)    
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 104, in update
    self._scan_update(self.scan_for_mapbuild, scans_mm)
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 136, in _scan_update
    scan.update(scans_mm=lidar, hole_width_mm=self.hole_width_mm, velocities=self.velocities)
TypeError: Wrong/insufficient arguments passed to Scan.update(): lidar size mismatch
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
_run:_get_scan:  echo of the command does not match (line @1):
_run:_find_packet_start: not connected to the sensor!
```

another try gave me this

```
init done 
opengl support available 
Traceback (most recent call last):
  File "./BreezySLAM/examples/urgslam.py", line 53, in <module>
_run:_get_scan:  echo of the command does not match (line @1):
    slam.update(lidar.getScan())
_run:_find_packet_start: not connected to the sensor!
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 254, in update
    CoreSLAM.update(self, scan_mm, velocities)    
_run:_get_scan:  echo of the command does not match (line @1):
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 104, in update
_run:_find_packet_start: not connected to the sensor!
    self._scan_update(self.scan_for_mapbuild, scans_mm)
  File "/usr/local/lib/python2.7/dist-packages/breezyslam/algorithms.py", line 136, in _scan_update
    scan.update(scans_mm=lidar, hole_width_mm=self.hole_width_mm, velocities=self.velocities)
TypeError: Wrong/insufficient arguments passed to Scan.update(): lidar size mismatch
```

May be an error that we could catch somewhere? would that be in the Python code?

**Comment by simondlevy** [comment]
Again, this is a deep problem in the BreezyLidar code (extension code in C) that I unfortunately cannot reproduce and hence cannot fix.
